version: "3.9"
services:
  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - 127.0.0.1:${PORT:-3000}:80
    links:
      - backend
  backend:
    build: ./backend
    restart: unless-stopped
    volumes:
      - devLog:/var/log
    links:
      - redis
  redis:
    image: redis
    restart: unless-stopped
volumes:
  devLog: {}